spring:
  application:
    name: homework1

#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: some-password
#    key-alias: springboot
#  port: 8443
#  http:
#    port: 8080


app:
  log-file: "${LOG_PATH}"