spring:
  application:
    name: homework1

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles:
        app.log.processing.time: 0.5,0.95,0.99
  prometheus:
    metrics:
      export:
        enabled: true


app:
  log-file: "${LOG_PATH}"